services:
  push-dev-devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      pull: false
    pull_policy: never
    init: true
    working_dir: /workspace
    volumes:
      - ..:/workspace
      - ../src:/src:ro
      - ../build:/out
