services:
  push-hello-world-devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      pull: false
    pull_policy: never
    container_name: push-hello-world-devcontainer
    init: true
    restart: unless-stopped
    working_dir: /workspace
    volumes:
      - ..:/workspace
      - ../src:/src:ro
      - ../build:/out
