#syntax=docker/dockerfile:1
FROM ableton-os-devcontainer:latest

echo "Hello World!"

echo "You can add your own commands to this Dockerfile to customize the devcontainer environment."
echo "For example, you can install additional packages, set environment variables, or run scripts."
